# Preliminary data, someone please PR a full set!!

Categories = [
    "Music",
    "Podcast"
]

Genres = [
    # Music
    "Top 40",
    "Pop",
    "Rap",
    "Hip-Hop",
    "Jazz",
    "Anime",
    # Podcast
    "Politics"
]

Countries = [
    "US",
    "UK",
    "Spain",
    "Germany",
    "Europe (English)",
    "Europe (Other)",
]

# Bots used for Shard Reporting
Bots = [
    "Main",
    "Patron 1",
    "Patron 2",
]